name = "LightKrylov"
version = "0.1.0"
license = "BSD-3-Clause"
author = "Jean-Christophe Loiseau"
maintainer = "jean-christophe.loiseau@ensam.eu"
copyright = "Copyright 2023, Jean-Christophe Loiseau"
description = "Lightweight fortran implementation of Krylov subspace techniques"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
external-modules = "mpi_f08"

[install]
library = true

[fortran]
implicit-typing = false
implicit-external = true
source-form = "free"

[dependencies]
stdlib = "*"
FACE = {git="https://github.com/szaghi/FACE.git"}

[dev-dependencies]
test-drive.git = "https://github.com/nekStab/test-drive.git"
FACE = {git="https://github.com/szaghi/FACE.git"}
SpecialMatrices = {git="https://github.com/loiseaujc/SpecialMatrices.git"}

[[example]]

#---------------------------------------------------------
#-----     SETUP FOR THE GINZBURG-LANDAU EXAMPLE     -----
#---------------------------------------------------------

name = "Ginzburg-Landau"
source-dir = "example/ginzburg_landau"

[example.dependencies]
rklib = { git="https://github.com/jacobwilliams/rklib.git" }

[[example]]

#----------------------------------------------
#-----     SETUP FOR ROESSLER EXAMPLE     -----
#----------------------------------------------

name = "Roessler"
source-dir = "example/roessler"

[example.dependencies]
rklib = { git="https://github.com/jacobwilliams/rklib.git" }
