arnoldi_factorization – LightKrylov
arnoldi_factorization Subroutine
FreeBSD Documentation License
78 statements
Source File
public subroutine arnoldi_factorization(A, X, H, info, kstart, kend, verbosity, tol, transpose, block_size)
Given a linear operator , find and such that:
where is an orthogonal basis and is an upper Hessenberg matrix.
Algorithmic Features
The operator only needs to be access through matrix-vector products.
Constructs an orthonormal Krylov basis X via modified Gram-Schmidt.
Constructs an upper Hessenberg matrix H.
Checks for convergence and invariant subspaces.
Advantages
Applicable for non-symmetric matrices.
Basis for many Krylov subspace methods.
Limitations
Orthogonality of X may deteriorate for ill-conditioned matrices.
Not suitable for preconditioning in this implementation.
References
Y. Saad. "Iterative methods for sparse linear systems", SIAM 2nd edition, 2003. see Chapter 6.3 : Arnoldi's method.
Arguments
Type Intent Optional Attributes Name
class(abstract_linop), intent(in) :: A
Linear operator to be factorized.
class(abstract_vector), intent(inout) :: X(:)
Orthogonal Krylov subspace. Note that on entry X(1) needs to be set to the initial Krylov vector.
real(kind=wp), intent(inout) :: H(:,:)
Upper Hessenberg matrix.
integer, intent(out) :: info
Information flag. On exit:
info < 0 : The k-step Arnoldi factorization failed.
info = 0 : The k-step Arnoldi factorization succeeded.
info > 0 : An invariant subspace has been computed after k=info steps.
integer, intent(in), optional :: kstart
Starting index for the Arnoldi factorization (default 1).
integer, intent(in), optional :: kend
Final index for the Arnoldi iteration (default size(X)-1).
logical, intent(in), optional :: verbosity
Verbosity control (default .false.).
real(kind=wp), intent(in), optional :: tol
Tolerance to determine whether an invariant subspace has been computed (default sqrt(epsilon(1.0_wp))).
logical, intent(in), optional :: transpose
Whether is being transposed or not (default .false.).
integer, intent(in), optional :: block_size
Block size for block Arnoldi (default 1).
Calls
Called by
Contents
Call graph
arnoldi_factorization calls optval, qr_factorization, assert_shape
qr_factorization calls optval, eye
two_sided_arnoldi_factorization calls arnoldi_factorization
eigs calls arnoldi_factorization