eigs – LightKrylov
eigs Subroutine
FreeBSD Documentation License
68 statements
Source File
public subroutine eigs(A, X, eigvals, residuals, info, nev, tolerance, verbosity, transpose)
Computes the leading eigenpairs of a linear operator A using its Arnoldi factorization. Given a square linear operator A of size (n x n), find eigvals and eigvecs such that:
or
The Krylov subspace X is constructed via Arnoldi factorization, resulting in an upper Hessenberg matrix H. The eigenvalues of A are approximated by the eigenvalues of H, and the eigenvectors are computed accordingly.
Algorithmic Features
Builds a Krylov subspace (X) using Arnoldi factorization.
Computes eigenpairs of the reduced upper Hessenberg matrix (H).
Sorts eigvals and associated eigvecs based on magnitude.
Advantages
Suitable for a wide range of square matrices A, including non-symmetric ones.
Efficient for large-scale problems.
Allows user-specified initial Krylov vector (X(1)).
Limitations
Accuracy is dependent on the quality of the initial Krylov vector.
No preconditioning capabilities in the current implementation.
References
Arnoldi, W. E. (1951). "The Principle of Minimized Iterations in the Solution of the Matrix Eigenvalue Problem." Quarterly of Applied Mathematics, 9(1), 17–29.
Arguments
Type Intent Optional Attributes Name
class(abstract_linop), intent(in) :: A
Linear operator whose leading eigenpairs need to be computed.
class(abstract_vector), intent(inout) :: X(:)
Leading eigenvectors of . On entry, X(1) needs to be set to the starting Krylov vector. On exit, storage of the real and imaginary parts of the eigenvectors follows the LAPACK convention.
complex(kind=wp), intent(out) :: eigvals(:)
Leading eigenvalues of .
real(kind=wp), intent(out) :: residuals(:)
Residual associated with each computed Ritz eigenpair.
integer, intent(out) :: info
Information flag.
integer, intent(in), optional :: nev
Desired number of eigenpairs.
real(kind=wp), intent(in), optional :: tolerance
Tolerance to determine whether a Ritz eigenpair has converged or not (default sqrt(epsilon(1.0_wp))).
logical, intent(in), optional :: verbosity
Verbosity control (default .false.)
logical, intent(in), optional :: transpose
Determine whether (default .false.) or (.true.) is used.
Calls
Contents
Call graph
eigs calls optval, arnoldi_factorization, eig, initialize_krylov_subspace, sort_index, mat_mult
arnoldi_factorization calls optval, qr_factorization, assert_shape
initialize_krylov_subspace calls qr_factorization, mat_zero, mat_copy
qr_factorization calls optval, eye
mat_copy calls mat_axpby