expm – LightKrylov
expm Subroutine
FreeBSD Documentation License
48 statements
Source File
public subroutine expm(E, A, order)
Computes the matrix exponential for a real-valued dense square matrix of order using the scaling and squaring approach, where the scaled problem is computed using a rational matrix Pade approximation of the form
where and are the respective orders of the matrix polynomials and .
Algorithmic Features
Only diagonal approximations () are used as these are more efficient to compute than off-diagonal approximations for the same approximation order
12th order diagonal Pade approximation by default
Advantages
Very accurate for "small" matrices (in terms of their norm). When considering the temporal evolution of an LTI system, i.e. , the approximation is very good for small .
Avoids numerical problems linked to the "hump" appearing for non-normal matrices
Limitations
No error estimation/check based on the approximation order and the matrix norm
expm is an adaptation of the function R8mat_expm1 by C. Moler & C. van Loan.
Original licensing:
This code is distributed under the MIT license.
References
C. Moler & C. Van Loan, "Nineteen Dubious Ways to Compute the Exponential of a Matrix, Twenty-Five Years Later", SIAM Review, Volume 45, Number 1, March 2003, pages 3-49.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(out) :: E(:,:)
Output
real(kind=wp), intent(in) :: A(:,:)
Square matrix to be exponentiated
integer, intent(in), optional :: order
Order of the Pade approximation
Calls
Contents
Call graph
expm calls optval, log2, norml, inv