gmres – LightKrylov
gmres Subroutine
FreeBSD Documentation License
124 statements
Source File
public subroutine gmres(A, b, x, info, preconditioner, options, transpose)
Implements the classic, unpreconditioned Generalized Minimal Residual (GMRES) algorithm for solving nonsymmetric linear systems of equations .
Algorithmic Features
Constructs a size-m Krylov subspace.
Utilizes Arnoldi factorization to generate an orthonormal basis for the Krylov subspace.
Employs a least-squares solve to determine the optimal linear combination of the Krylov vectors.
Updates the approximate solution based on the least-squares solution.
*Advantages
Suitable for nonsymmetric and ill-conditioned matrices.
Produces monotonically decreasing residuals.
Limitations
Original gmres uses Givens rotations to update the least-squares solution. For the sake of simplicity, we use directly the lstsq solver from LAPACK.
References
Saad, Y., and Schultz, M. H. (1986). "GMRES: A Generalized Minimal Residual Algorithm for Solving Nonsymmetric Linear Systems," SIAM Journal on Scientific and Statistical Computing, 7(3), 856–869.
Arguments
Type Intent Optional Attributes Name
class(abstract_linop), intent(in) :: A
Linear operator to be inverted.
class(abstract_vector), intent(in) :: b
Right-hand side vector.
class(abstract_vector), intent(inout) :: x
Solution vector.
integer, intent(out) :: info
Information flag.
class(abstract_preconditioner), intent(in), optional :: preconditioner
Preconditioner.
class(abstract_opts), intent(in), optional :: options
Options.
logical, intent(in), optional :: transpose
Whether (.false.) or (.true.) is used.
Calls
Contents
Call graph
gmres calls optval, lstsq, initialize_krylov_subspace, get_vec
lstsq calls dgels, stop_error
initialize_krylov_subspace calls mat_zero, mat_copy, qr_factorization
mat_copy calls mat_axpby
qr_factorization calls optval, eye