initialize_krylov_subspace – LightKrylov
initialize_krylov_subspace Subroutine
FreeBSD Documentation License
26 statements
Source File
public subroutine initialize_krylov_subspace(X, B0)
Utility function to initializes an array of abstract_vector. By default, it initializes X to an array of zero abstract_vectors. If B0 is passed, it initializes the first p columns of X with the content of B0 followed by orthogonalization.
Arguments
Type Intent Optional Attributes Name
class(abstract_vector), intent(inout) :: X(:)
Array of abstract_vector to initialize.
class(abstract_vector), intent(in), optional :: B0(:)
If present, the span of the first p columns.
Calls
Called by
Contents
Call graph
initialize_krylov_subspace calls mat_zero, mat_copy, qr_factorization
mat_copy calls mat_axpby
qr_factorization calls eye, optval
krylov_schur_restart calls initialize_krylov_subspace
eigs calls initialize_krylov_subspace
svds calls initialize_krylov_subspace
eighs calls initialize_krylov_subspace
gmres calls initialize_krylov_subspace