krylov_schur_restart – LightKrylov
krylov_schur_restart Subroutine
FreeBSD Documentation License
54 statements
Source File
public subroutine krylov_schur_restart(nblk, X, H, select_eigs, blksize)
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: nblk
Number of blocks (or vectors if blksize=1) that have been moved to the upper left block of the Schur factorization of H.
class(abstract_vector), intent(inout) :: X(:)
Krylov basis.
real(kind=wp), intent(inout) :: H(:,:)
Hessenberg/Schur matrix of the Krylov decomposition.
procedure(selector) :: select_eigs
Routine to select the eigenvalues that need to be moved in the upper left block of the Schur factorization. Its interface needs to be compliant with
 interface
    function selector(lambda) result(out)
      import wp
      complex(kind=wp), intent(in) :: lambda(:)
      logical                      :: out(size(lambda))
    end function selector
 end interface
integer, intent(in), optional :: blksize
Block-size if block Arnoldi is being used (default blksize = 1).
Warning
The routine will return an error if blksize /= 1. This is related to an issue with the current implement if the number of selected eigenvalues is not a multiple of the block size.
Calls
Contents
Call graph
krylov_schur_restart calls optval, mat_mult, ordschur, schur, stop_error, initialize_krylov_subspace
ordschur calls dtrsen
schur calls dgees
initialize_krylov_subspace calls mat_zero, mat_copy, qr_factorization
mat_copy calls mat_axpby
qr_factorization calls optval, eye