lstsq – LightKrylov
lstsq Subroutine
FreeBSD Documentation License
27 statements
Source File
public subroutine lstsq(A, b, x)
Solves a linear least-squares problem using LAPACK.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in), dimension(:, :) :: A
Matrix to be "pseudo-inverted".
real(kind=wp), intent(in), dimension(:) :: b
Right-hand side vector.
real(kind=wp), intent(out), dimension(:) :: x
Solution of the least-squares problem.
Calls
Called by
Contents
Call graph
lstsq calls dgels, stop_error
gmres calls lstsq