mat_zero – LightKrylov
mat_zero Subroutine
FreeBSD Documentation License
7 statements
Source File
public subroutine mat_zero(A)
Initialize an array of abstract_vector to zero by repeatedly calling A(i)%zero() for i = 1, size(A).
Arguments
Type Intent Optional Attributes Name
class(abstract_vector), intent(inout) :: A(:)
Array of abstract_vector to be zeroed-out.
Called by
Contents
Call graph
initialize_krylov_subspace calls mat_zero
eigs calls initialize_krylov_subspace
svds calls initialize_krylov_subspace
gmres calls initialize_krylov_subspace
krylov_schur_restart calls initialize_krylov_subspace
eighs calls initialize_krylov_subspace