qr_factorization – LightKrylov
qr_factorization Subroutine
FreeBSD Documentation License
104 statements
Source File
public subroutine qr_factorization(Q, R, perm, info, ifpivot, verbosity, tol)
Orthogonalization of an array of abstract_vector using the modified Gram-Schmid process with or without column pivoting.
Algorithmic Features
In-place factorization
Modified / Double Gram-Schmidt procedure for stability
Includes a simple check for premature breakdown
Advantages
Suitable for all Krylov subspace dimensions
Robust with respect to floating point errors
Optional pivoting to deal with rank-deficient Krylov bases
Limitations
The current implementation only includes a simple check for breakdown
References
G. H. Golub & C. F. Van Loan. "Matrix Computations". 4th edition, The John Hopkins University Press, 2013. See Chapter 5.2.8 : Modified Gram-Schmidt algorithm. Orthonormalize against existing columns
Arguments
Type Intent Optional Attributes Name
class(abstract_vector), intent(inout) :: Q(:)
Array of abstract_vector that need to be orthogonalized.
real(kind=wp), intent(out) :: R(:,:)
Upper triangular matrix resulting from the QR factoriation.
integer, intent(out) :: perm(size(Q))
Permutation matrix.
integer, intent(out) :: info
Information flag.
logical, intent(in), optional :: ifpivot
QR with (.true.) or without (.false.) column pivoting.
logical, intent(in), optional :: verbosity
Verbosity control (default .false.).
real(kind=wp), intent(in), optional :: tol
Tolerance to determine colinearity (default sqrt(epsilon(1.0_wp))).
Calls
Called by
Contents
Call graph
qr_factorization calls optval
initialize_krylov_subspace calls qr_factorization
arnoldi_factorization calls qr_factorization
eigs calls initialize_krylov_subspace, arnoldi_factorization
svds calls initialize_krylov_subspace
gmres calls initialize_krylov_subspace
krylov_schur_restart calls initialize_krylov_subspace
eighs calls initialize_krylov_subspace
two_sided_arnoldi_factorization calls arnoldi_factorization