svds – LightKrylov
svds Subroutine
FreeBSD Documentation License
67 statements
Source File
public subroutine svds(A, U, V, sigma, residuals, info, nev, tolerance, verbosity)
Computes the singular value decomposition of a given linear operator using Lanczos bidiagonalization. The subroutine finds matrices , , and such that
Algorithmic Features
Relies on Lanczos bidiagonalization.
Computes the singular value decomposition of of a small bidiagonal matrix to obtain approximate singular values and vectors of .
Calculates residuals for singular triplets.
Optionally verbose, providing runtime diagnostics.
Advantages
Efficient for large, sparse matrices.
Suitable for problems requiring only a subset of singular values and vectors.
Can be adapted for preconditioning techniques.
Limitations
Not optimized for dense matrices or those with special structures (e.g., Toeplitz, circulant).
May require many iterations for ill-conditioned matrices.
Only a full re-orthogonalization scheme is implemented.
References
Golub, G. H., & Kahan, W. (1965). "Calculating the Singular Values and Pseudo-Inverse of a Matrix."
Baglama, J., & Reichel, L. (2005). "Augmented implicitly restarted Lanczos bidiagonalization methods."
R. M. Larsen. "Lanczos bidiagonalization with partial reorthogonalization." Technical Report, 1998. (PDF)
Arguments
Type Intent Optional Attributes Name
class(abstract_linop), intent(in) :: A
Linear operator whose leading singular triplets are to be computed.
class(abstract_vector), intent(inout) :: U(:)
Leading left singular vectors of . On entry, U(1) needs to be set to the starting Krylov vector.
class(abstract_vector), intent(inout) :: V(:)
Leading right singular vectors of .
real(kind=wp), intent(out) :: sigma(:)
Leading singular values.
real(kind=wp), intent(out) :: residuals(:)
Residual associated to each Ritz singular triplet.
integer, intent(out) :: info
Information flag.
integer, intent(in), optional :: nev
Desired number of converged singular triplets.
real(kind=wp), intent(in), optional :: tolerance
Tolerance to check convergence of each triplet.
logical, intent(in), optional :: verbosity
Verbosity control.
Calls
Contents
Call graph
svds calls optval, mat_mult, lanczos_bidiagonalization, initialize_krylov_subspace, svd
lanczos_bidiagonalization calls optval, assert_shape
initialize_krylov_subspace calls mat_zero, mat_copy, qr_factorization
mat_copy calls mat_axpby
qr_factorization calls optval, eye