two_sided_arnoldi_factorization – LightKrylov
two_sided_arnoldi_factorization Subroutine
FreeBSD Documentation License
74 statements
Source File
public subroutine two_sided_arnoldi_factorization(A, V, W, H, G, info, kstart, kend, verbosity, tol)
Check Krylov subspace dimensions. Check the dimensions of the Hessenberg matrices. Deals with the optional arguments. Arnoldi step for the image. Arnoldi step for the domain. Inner-product matrix.
Inverse of the inner-product matrix (in-place).
Update the residual vectors. Rayleigh Quotient form of the Hessenberg matrices.
Arguments
Type Intent Optional Attributes Name
class(abstract_linop), intent(in) :: A
Linear operator to be factorized.
class(abstract_vector), intent(inout) :: V(:)
Left and right Krylov basis.
class(abstract_vector), intent(inout) :: W(:)
real(kind=wp), intent(inout) :: H(:,:)
Upper Hessenberg matrices.
real(kind=wp), intent(inout) :: G(:,:)
Upper Hessenberg matrices.
integer, intent(out) :: info
Information flag.
integer, intent(in), optional :: kstart
Optional arguments.
integer, intent(in), optional :: kend
logical, intent(in), optional :: verbosity
real(kind=wp), intent(in), optional :: tol
Calls
Contents
Call graph
two_sided_arnoldi_factorization calls assert_shape, optval, arnoldi_factorization, inv
arnoldi_factorization calls assert_shape, optval, qr_factorization
qr_factorization calls optval, eye