#:include "../../include/common.fypp"
#:set RC_KINDS_TYPES = REAL_KINDS_TYPES + CMPLX_KINDS_TYPES
#:def CHECK_NAN(beta, varname)
    if (isnan(${beta}$)) call stop_error('|' // ${varname}$ // '| = NaN detected! Abort', this_module, this_procedure)
#:enddef
submodule (lightkrylov_basekrylov) qr_solvers
    implicit none(type, external)

    interface swap_columns
        #: for kind, type in RC_KINDS_TYPES
        module subroutine swap_columns_${type[0]}$${kind}$(Q, R, Rii, perm, i, j)
            implicit none(type, external)
            class(abstract_vector_${type[0]}$${kind}$), intent(inout) :: Q(:)
            !! Vector basis whose i-th and j-th columns need swapping.
            ${type}$, intent(inout) :: R(:, :)
            !! Upper triangular matrix resulting from QR.
            real(${kind}$), intent(inout) :: Rii(:)
            !! Squared diagonal entries of R.
            integer, intent(inout) :: perm(:)
            !! Permutation vector.
            integer, intent(in) :: i, j
            !! Index of the columns to be swapped.
        end subroutine swap_columns_${type[0]}$${kind}$

        #:endfor
    end interface

contains

    !------------------------------------
    !-----     QR WITH PIVOTING     -----
    !------------------------------------

    #:for kind, type in RC_KINDS_TYPES
    module procedure qr_with_pivoting_${type[0]}$${kind}$
        character(len=*), parameter :: this_procedure = 'qr_with_pivoting_${type[0]}$${kind}$'
        real(${kind}$) :: tolerance
        real(${kind}$) :: alpha, beta
        ${type}$ :: gamma
        integer :: idx, i, j, kdim, ierr
        integer :: idxv(1)
        real(${kind}$)  :: Rii(size(Q))
        character(len=128) :: msg

        if (time_lightkrylov()) call timer%start(this_procedure)

        kdim = size(Q) ; R = zero_r${kind}$

        ! Deals with the optional arguments.
        tolerance = optval(tol, atol_${kind}$)

        ! Sanity checks.
        if (size(Q) < 1) then
            info = -1
        else if (size(R, 1) < size(Q) .or. size(R, 2) < size(Q)) then
            info = -2
        else if (size(perm) < size(Q)) then
            info = -3
        else if (tolerance < 0) then
            info = -4
        else
            info = 0
        endif

        if (info == 0) then
            ! Initialize diagonal entries.
            do i = 1, kdim
                perm(i) = i
                Rii(i) = real(Q(i)%dot(Q(i)), kind=${kind}$)
            enddo

            qr_step: do j = 1, kdim
                idxv = j - 1 + maxloc(Rii(j:kdim)) ; idx = idxv(1)
                call swap_columns(Q, R, Rii, perm, j, idx)

                ! Check for breakdown.
                beta = Q(j)%norm()
                @:CHECK_NAN(beta, "beta")

                if (beta <= tolerance) then
                    ! Store old value of beta.
                    alpha = beta
                    ! Remaining columns are numerically in span(Q(1:j-1)): regenerate j..kdim.
                    do i = j, kdim
                        call Q(i)%rand()
                        if (i > 1) then
                            call double_gram_schmidt_step(Q(i), Q(:i-1), ierr, if_chk_orthonormal=.false.)
                            call check_info(ierr, 'double_gram_schmidt_step', this_module, this_procedure)
                        endif
                        beta = Q(i)%norm() ; call Q(i)%scal(one_${type[0]}$${kind}$ / beta)
                    enddo
                    info = j
                    write(msg,'(A,I0,A,E15.8)') 'Breakdown after ', j, ' steps. |beta|= ', abs(alpha)
                    call log_information(msg, this_module, this_procedure)
                    exit qr_step
                endif

                R(j, j) = beta
                call Q(j)%scal(one_${type[0]}$${kind}$ / beta)

                ! Orthogonalize all columns against new vector and update Rii.
                Rii(j) = zero_r${kind}$
                do i = j+1, kdim
                    gamma = Q(j)%dot(Q(i))
                    call Q(i)%axpby(-gamma, Q(j), one_${type[0]}$${kind}$)   ! Q(i) = Q(i) - gamma*Q(j)
                    R(j, i) = gamma
                    Rii(i) = real(Q(i)%dot(Q(i)), kind=${kind}$)
                enddo

            enddo qr_step
        endif

        if (time_lightkrylov()) call timer%stop(this_procedure)
    end procedure qr_with_pivoting_${type[0]}$${kind}$

    #:endfor

    !---------------------------------------------
    !-----     STANDARD QR FACTORIZATION     -----
    !---------------------------------------------

    #:for kind, type in RC_KINDS_TYPES
    module procedure qr_no_pivoting_${type[0]}$${kind}$
        character(len=*), parameter :: this_procedure = 'qr_no_pivoting_${type[0]}$${kind}$'
        real(${kind}$) :: tolerance
        real(${kind}$) :: beta
        ${type}$ :: gamma
        integer :: j, ierr
        logical :: flag
        character(len=128) :: msg

        if (time_lightkrylov()) call timer%start(this_procedure)

        ! Deals with the optional args.
        tolerance = optval(tol, atol_${kind}$)

        ! Sanity checks.
        if (size(Q) < 1) then
            info = -1
        else if (size(R, 1) < size(Q) .or. size(R, 2) < size(Q)) then
            info = -2
        else if (tolerance < 0) then
            info = -4
        else
            info = 0
        endif

        if (info == 0) then
            flag = .false.
            R = zero_r${kind}$
            beta = zero_r${kind}$
            do j = 1, size(Q)
                if (j > 1) then
                    ! Double Gram-Schmidt orthogonalization
                    call double_gram_schmidt_step(Q(j), Q(:j-1), ierr, &
                                                  if_chk_orthonormal=.false., beta = R(:j-1,j))
                    call check_info(ierr, 'double_gram_schmidt_step', this_module, this_procedure)
                end if

                ! Check for breakdown.
                beta = Q(j)%norm()
                @:CHECK_NAN(beta, "beta")
                if (beta <= tolerance) then
                    if (.not.flag) then
                        flag = .true.
                        info = j
                        write(msg,'(A,I0,A,E15.8)') 'Colinear column detected after ', j, ' steps. beta= ', beta
                        call log_information(msg, this_module, this_procedure)
                    end if
                    R(j, j) = zero_r${kind}$
                    call Q(j)%rand()
                    if (j > 1) then
                        call double_gram_schmidt_step(Q(j), Q(:j-1), ierr, if_chk_orthonormal=.false.)
                        call check_info(ierr, 'double_gram_schmidt_step', this_module, this_procedure)
                    end if
                    beta = Q(j)%norm()
                else
                    R(j, j) = beta
                endif
                ! Normalize column.
                call Q(j)%scal(one_${type[0]}$${kind}$ / beta)
            enddo
        endif

        if (time_lightkrylov()) call timer%stop(this_procedure)
    end procedure qr_no_pivoting_${type[0]}$${kind}$

    #:endfor

    !-------------------------------------
    !-----     Utility functions     -----
    !-------------------------------------

    #:for kind, type in RC_KINDS_TYPES
    module procedure swap_columns_${type[0]}$${kind}$
        class(abstract_vector_${type[0]}$${kind}$), allocatable :: Qwrk
        ${type}$, allocatable :: Rwrk(:)
        integer :: iwrk, m, n, iostat
        character(len=100) :: errmsg

        ! Sanity checks.
        m = size(Q) ; n = min(i, j) - 1

        ! Columns already in the correct order.
        if (i == j) return

        ! Allocations.
        allocate(Qwrk, mold=Q(1), stat=iostat, errmsg=errmsg)
        call check_allocation(iostat, errmsg, this_module, "swap_columns_${type[0]}$${kind}$")
        allocate(Rwrk(max(1, n)), source=zero_${type[0]}$${kind}$, stat=iostat, errmsg=errmsg)
        call check_allocation(iostat, errmsg, this_module, "swap_columns_${type[0]}$${kind}$")

        ! Swap columns.
        call copy(Qwrk, Q(j))
        call copy(Q(j), Q(i))
        call copy(Q(i), Qwrk)

        Rwrk(1) = Rii(j); Rii(j) = Rii(i); Rii(i) = real(Rwrk(1), kind=${kind}$)
        iwrk = perm(j); perm(j) = perm(i) ; perm(i) = iwrk

        if (n > 0) then
            Rwrk = R(:n, j) ; R(:n, j) = R(:n, i) ; R(:n, i) = Rwrk
        endif
    end procedure swap_columns_${type[0]}$${kind}$

    #:endfor
end submodule qr_solvers
