assert_shape – LightKrylov
assert_shape Interface
FreeBSD Documentation License
4 statements
Source File
public interface assert_shape
Interface to assert the shape of a matrix.
Called by
Contents
Module Procedures
dassert_shape zassert_shape
Module Procedures
private subroutine dassert_shape(A, size, routine, matname)
Utility function to assert the shape of a real-valued matrix.
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: A(:,:)
Matrix whose dimensions need to be asserted.
integer, intent(in) :: size(:)
Expected dimensions of A.
character(len=*), intent(in) :: routine
Name of the routine where assertion is done.
character(len=*), intent(in) :: matname
Name of the asserted matrix.
private subroutine zassert_shape(A, size, routine, matname)
Utility function to assert the shape of a complex-valued matrix.
Arguments
Type Intent Optional Attributes Name
complex(kind=wp), intent(in) :: A(:,:)
Matrix whose dimensions need to be asserted.
integer, intent(in) :: size(:)
Expected dimensions of A.
character(len=*), intent(in) :: routine
Name of the routine where assertion is done.
character(len=*), intent(in) :: matname
Name of the asserted matrix.
Call graph
arnoldi_factorization calls assert_shape
lanczos_bidiagonalization calls assert_shape
lanczos_tridiagonalization calls assert_shape
rational_arnoldi_factorization calls assert_shape
sqrtm calls assert_shape
two_sided_arnoldi_factorization calls assert_shape, arnoldi_factorization
eigs calls arnoldi_factorization
svds calls lanczos_bidiagonalization
eighs calls lanczos_tridiagonalization