name: Docs
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  publish:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Documentation
        uses: loiseaujc/ford-build@v1.0
        id: build

      - name: Deploy to GitHub Pages
        if: steps.build.outcome == 'success'
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: API-doc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
